-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE public.hari AS ENUM 
(
    'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'
);

CREATE TABLE IF NOT EXISTS public.cabang_toko
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    alamat_jalan character varying(256) NOT NULL,
    kabupaten_kota character varying(128) NOT NULL,
    kecamatan character varying(128) NOT NULL,
    provinsi character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    nomor_telp character varying(128) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.buku
(
    id integer UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
    judul character varying(256) UNIQUE NOT NULL,
    ISBN character varying(256) UNIQUE NOT NULL,
    tanggal_rilis date NOT NULL,
    halaman bigint NOT NULL,
    foto text DEFAULT NULL,
    last_update timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    penerbit integer NOT NULL,
    PRIMARY KEY (id, ISBN)
);

CREATE TABLE IF NOT EXISTS public.pegawai
(
    id integer UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
    nama character varying(256) NOT NULL,
    nik character varying(24) UNIQUE NOT NULL,
    nomor_rekening character varying(128) NOT NULL,
    kabupaten_kota character varying(128) NOT NULL,
    alamat_jalan character varying(256) NOT NULL,
    kecamatan character varying(128) NOT NULL,
    provinsi character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    nomor_hp character varying(128) NOT NULL,
    gaji bigint NOT NULL,
    status_aktif boolean NOT NULL,
    id_cabang integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    last_Updated timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, nik)
);

CREATE TABLE IF NOT EXISTS public.akun_user
(
    id integer UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
    username character varying(128) UNIQUE NOT NULL,
    nama_panjang character varying(128) NOT NULL,
    nomor_telp character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, username)
);

CREATE TABLE IF NOT EXISTS public.penerbit
(
    id integer UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
    alamat_jalan character varying(256) NOT NULL,
    kabupaten_kota character varying(128) NOT NULL,
    kecamatan character varying(128) NOT NULL,
    provinsi character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    nomor_telp character varying(128) NOT NULL,
    nama character varying(128) UNIQUE NOT NULL,
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, nama)
);

CREATE TABLE IF NOT EXISTS public.penulis
(
    id integer UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
    alamat_jalan character varying(256),
    kabupaten_kota character varying(128),
    kecamatan character varying(128),
    provinsi character varying(128),
    email character varying(128),
    nomor_telp character varying(128),
    nama character varying(128) NOT NULL,
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.genre
(
    id integer UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
    nama character varying UNIQUE NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, nama)
);

CREATE TABLE IF NOT EXISTS public.wishlist
(
    id_user integer UNIQUE NOT NULL,
    id_buku integer UNIQUE NOT NULL,
    created_at time without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_user, id_buku)
);

CREATE TABLE IF NOT EXISTS public.rating_buku
(
    id_buku integer NOT NULL,
    id_user integer NOT NULL,
    rating integer NOT NULL DEFAULT 0,
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
	review_tulisan character varying(128),
    PRIMARY KEY (id_buku, id_user),
    UNIQUE (id_buku, id_user)
);

CREATE TABLE IF NOT EXISTS public.promo
(
    id integer NOT NULL,
    deksripsi text,
    tanggal_mulai timestamp without time zone NOT NULL,
    tanggal_terakhir timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    judul text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.relasi_buku_promo
(
    id_promo integer NOT NULL,
    id_buku integer NOT NULL,
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    diskon integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id_promo, id_buku),
    UNIQUE (id_promo, id_buku)
);

CREATE TABLE IF NOT EXISTS public.relasi_buku_genre
(
    id_genre integer NOT NULL,
    id_buku integer NOT NULL,
    PRIMARY KEY (id_buku, id_genre),
	UNIQUE (id_buku, id_genre)
);

CREATE TABLE IF NOT EXISTS public.relasi_cabang_buku
(
    id_buku integer NOT NULL,
    id_cabang integer NOT NULL,
    kuantitas integer NOT NULL,
    harga bigint NOT NULL,
    last_updated time without time zone NOT NULL DEFAULT NOW(),
    created_at time without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_buku, id_cabang),
	UNIQUE (id_buku, id_cabang)
);

CREATE TABLE IF NOT EXISTS public.jam_buka
(
    id_cabang integer NOT NULL,
    hari hari NOT NULL,
    jam_buka time without time zone NOT NULL,
    jam_tutup time without time zone NOT NULL,
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_cabang, hari),
	UNIQUE (id_cabang, hari)
);

CREATE TABLE IF NOT EXISTS public.relasi_penulis_buku
(
    id_buku integer NOT NULL,
    id_penulis integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    last_updated timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_buku, id_penulis),
	UNIQUE (id_buku, id_penulis)
);


ALTER TABLE IF EXISTS public.buku
    ADD CONSTRAINT penerbit FOREIGN KEY (penerbit)
    REFERENCES public.penerbit (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.pegawai
    ADD CONSTRAINT cabang_toko FOREIGN KEY (id_cabang)
    REFERENCES public.cabang_toko (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.wishlist
    ADD CONSTRAINT id_akun FOREIGN KEY (id_user)
    REFERENCES public.akun_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.wishlist
    ADD CONSTRAINT id_buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id) MATCH FULL
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rating_buku
    ADD CONSTRAINT akun FOREIGN KEY (id_user)
    REFERENCES public.akun_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rating_buku
    ADD CONSTRAINT buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.relasi_buku_promo
    ADD CONSTRAINT promo FOREIGN KEY (id_promo)
    REFERENCES public.promo (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.relasi_buku_promo
    ADD CONSTRAINT buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.relasi_buku_genre
    ADD CONSTRAINT buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.relasi_buku_genre
    ADD CONSTRAINT genre FOREIGN KEY (id_genre)
    REFERENCES public.genre (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.relasi_cabang_buku
    ADD FOREIGN KEY (id_buku)
    REFERENCES public.buku (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.relasi_cabang_buku
    ADD FOREIGN KEY (id_cabang)
    REFERENCES public.cabang_toko (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.jam_buka
    ADD FOREIGN KEY (id_cabang)
    REFERENCES public.cabang_toko (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.relasi_penulis_buku
    ADD CONSTRAINT buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

ALTER TABLE IF EXISTS public.relasi_penulis_buku
    ADD CONSTRAINT penulis FOREIGN KEY (id_penulis)
    REFERENCES public.penulis (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
COMMIT;
END;